// Generated by whippletree. Do not hand-edit; regenerate with `whippletree build`.
// opencode has no blocking stop event: a thrown error fails one tool call and
// the agent loop continues. Exit 2 from the dispatcher becomes that throw.
import { spawnSync } from "node:child_process"

const HOOK = "__WHIPPLETREE_HOOK__"
const TARGET = "opencode"

function dispatch(event: string, payload: unknown): void {
  const r = spawnSync(HOOK, ["run", event, "--target", TARGET], {
    input: JSON.stringify(payload), encoding: "utf8",
  })
  if (r.status === 2) throw new Error(r.stderr || "blocked by " + event + " hook")
}

export const Whippletree = async (ctx: any) => ({
  event: async (input: any) => {
    if (input?.event?.type === "session.created") {
      dispatch("session-start", { source: "opencode", hook: "event", payload: input, directory: ctx.directory })
    }
  },
  "tool.execute.after": async (input: any, output: any) => {
    if (input?.tool === "read") {
      dispatch("file-read", { source: "opencode", hook: "tool.execute.after", input, output, directory: ctx.directory })
    }
  },
})
