package compile

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"whippletree.dev/internal/contract"
	"whippletree.dev/internal/target"
)

// GeneratedByPrefix is the stable identity of a whippletree-generated
// file. install's overwrite protection matches on this prefix rather
// than the whole line, so the wording after it can change without a
// later whippletree refusing to overwrite what an earlier one wrote.
const GeneratedByPrefix = "// Generated by whippletree"

// GeneratedByLine is the full first line every ts-plugin shim carries.
// The URL is the point: whoever finds a generated file in a repo they
// did not build should be able to reach the project from it.
const GeneratedByLine = GeneratedByPrefix + " (https://whippletree.dev). Do not hand-edit; regenerate with `whippletree build`."

// tsPlugin accumulates a ts-plugin target's dispatch calls in
// first-seen insertion order over the contract's already-ordered
// requirement list, so the emitted shim is deterministic without an
// explicit sort.
type tsPlugin struct {
	order  []string
	groups map[string]*tsHookGroup
	seen   map[string]bool
}

type tsHookGroup struct {
	hookKey string
	twoArg  bool
	entries []tsHookEntry
}

// tsHookEntry is one requirement's dispatch call. An empty filterExpr
// means the call is unconditional; dispatchEvent is the contract's own
// event name, alias or primitive, not the resolved one.
type tsHookEntry struct {
	filterExpr    string
	dispatchEvent string
}

func newTSPlugin() *tsPlugin {
	return &tsPlugin{groups: make(map[string]*tsHookGroup), seen: make(map[string]bool)}
}

// add appends entry to hookKey's group, dropping an exact repeat so two
// requirements resolving to the same guarded call emit it once.
func (p *tsPlugin) add(hookKey string, twoArg bool, entry tsHookEntry) {
	key := hookKey + "\x00" + entry.filterExpr + "\x00" + entry.dispatchEvent
	if p.seen[key] {
		return
	}
	p.seen[key] = true

	g, ok := p.groups[hookKey]
	if !ok {
		g = &tsHookGroup{hookKey: hookKey, twoArg: twoArg}
		p.groups[hookKey] = g
		p.order = append(p.order, hookKey)
	}
	g.entries = append(g.entries, entry)
}

// addTSHookEntry appends req's dispatch call onto p. Matcher resolution
// goes through matcherFor, the hooks-json emitter's own helper, so a
// ts-plugin target degrades exactly the way a hooks-json target does.
func addTSHookEntry(p *tsPlugin, req contract.Requirement, td *target.Def, name string) error {
	primitive, toolClass, err := contract.ResolveEvent(req.Event)
	if err != nil {
		return fmt.Errorf("requirement %s: %w", req.ID, err)
	}

	mapping, ok := td.Events[primitive]
	if !ok {
		return fmt.Errorf("requirement %s: target %q has no mapping for primitive %q", req.ID, name, primitive)
	}

	matcher := matcherFor(req, td, toolClass)
	hookKey, filterExpr, twoArg := tsHookShape(mapping.Native, matcher)

	p.add(hookKey, twoArg, tsHookEntry{filterExpr: filterExpr, dispatchEvent: req.Event})
	return nil
}

// opencode wraps its bus events under a single literal "event" hook:
// a native string of the form "event:<type>" names the bus event type
// to filter on. Every other native string names a two-argument tool
// hook directly (verified against internal/dispatch/testdata/opencode-probe:
// the tool id lives on input.tool in both tool.execute.before and
// tool.execute.after), filtered on that tool id via matcher when one
// is known; with no matcher the hook fires unconditionally.
func tsHookShape(native, matcher string) (hookKey, filterExpr string, twoArg bool) {
	if rest, ok := strings.CutPrefix(native, "event:"); ok {
		return "event", fmt.Sprintf("input?.event?.type === %q", rest), false
	}
	if matcher != "" {
		return native, fmt.Sprintf("input?.tool === %q", matcher), true
	}
	return native, "", true
}

// renderTSPlugin renders the opencode shim for target name. The HOOK
// constant is left as a literal placeholder: resolving it to a real
// dispatcher path is install's job, not build's.
func renderTSPlugin(name string, p *tsPlugin) []byte {
	var b strings.Builder

	b.WriteString(GeneratedByLine + "\n")
	b.WriteString("// opencode has no blocking stop event: a thrown error fails one tool call and\n")
	b.WriteString("// the agent loop continues. Exit 2 from the dispatcher becomes that throw; a\n")
	b.WriteString("// spawn failure or any other non-zero exit is reported on stderr and ignored.\n")
	b.WriteString("import { spawnSync } from \"node:child_process\"\n")
	b.WriteString("\n")
	fmt.Fprintf(&b, "const HOOK = %q\n", "__WHIPPLETREE_HOOK__")
	fmt.Fprintf(&b, "const TARGET = %q\n", name)
	b.WriteString("\n")
	b.WriteString("function dispatch(event: string, payload: unknown): void {\n")
	b.WriteString("  const r = spawnSync(HOOK, [\"run\", event, \"--target\", TARGET], {\n")
	b.WriteString("    input: JSON.stringify(payload), encoding: \"utf8\",\n")
	b.WriteString("  })\n")
	b.WriteString("  if (r.error) {\n")
	b.WriteString("    console.error(\"whippletree: \" + event + \" dispatch failed to run: \" + r.error.message)\n")
	b.WriteString("    return\n")
	b.WriteString("  }\n")
	b.WriteString("  if (r.status === 2) throw new Error(r.stderr || \"blocked by \" + event + \" hook\")\n")
	b.WriteString("  if (r.status !== 0) {\n")
	b.WriteString("    console.error(\"whippletree: \" + event + \" dispatch exited \" + String(r.status) + (r.stderr ? \": \" + r.stderr : \"\"))\n")
	b.WriteString("  }\n")
	b.WriteString("}\n")
	b.WriteString("\n")
	b.WriteString("export const Whippletree = async (ctx: any) => ({\n")

	for _, hookKey := range p.order {
		writeTSHookGroup(&b, name, p.groups[hookKey])
	}

	b.WriteString("})\n")

	return []byte(b.String())
}

func tsObjectKey(hookKey string) string {
	if hookKey == "event" {
		return "event"
	}
	return fmt.Sprintf("%q", hookKey)
}

func writeTSHookGroup(b *strings.Builder, name string, g *tsHookGroup) {
	sig := "async (input: any) => {"
	if g.twoArg {
		sig = "async (input: any, output: any) => {"
	}
	fmt.Fprintf(b, "  %s: %s\n", tsObjectKey(g.hookKey), sig)

	payload := tsDispatchPayload(name, g.hookKey, g.twoArg)
	for _, e := range g.entries {
		if e.filterExpr != "" {
			fmt.Fprintf(b, "    if (%s) {\n", e.filterExpr)
			fmt.Fprintf(b, "      dispatch(%q, %s)\n", e.dispatchEvent, payload)
			b.WriteString("    }\n")
		} else {
			fmt.Fprintf(b, "    dispatch(%q, %s)\n", e.dispatchEvent, payload)
		}
	}

	b.WriteString("  },\n")
}

// tsDispatchPayload builds dispatch's second argument. The "event" hook
// only ever sees one argument, so the whole thing rides under payload.
func tsDispatchPayload(name, hookKey string, twoArg bool) string {
	if !twoArg {
		return fmt.Sprintf("{ source: %q, hook: %q, payload: input, directory: ctx.directory }", name, hookKey)
	}
	return fmt.Sprintf("{ source: %q, hook: %q, input, output, directory: ctx.directory }", name, hookKey)
}

// writeTSPluginFile writes hooks/<name>.ts. No manifest pair: opencode
// has no manifest for whippletree to extend.
func writeTSPluginFile(bundleDir, name string, p *tsPlugin) error {
	dir := filepath.Join(bundleDir, "hooks")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("create hooks dir for target %q: %w", name, err)
	}
	if err := os.WriteFile(filepath.Join(dir, name+".ts"), renderTSPlugin(name, p), 0o644); err != nil {
		return fmt.Errorf("write ts-plugin shim for target %q: %w", name, err)
	}
	return nil
}
